export const locations = [
  {value: "south-east", label: "South East"},
  {value: "surrey", label: "Surrey"},
  {value: "bracknell-forest", label: "Bracknell Forest"},
  {value: "southampton", label: "Southampton"},
  {value: "slough", label: "Slough"},
  {value: "milton-keynes", label: "Milton Keynes"},
  {value: "buckinghamshire", label: "Buckinghamshire"},
  {value: "wokingham", label: "Wokingham"},
  {value: "portsmouth", label: "Portsmouth"},
  {value: "medway", label: "Medway"},
  {value: "hampshire", label: "Hampshire"},
  {value: "west-sussex", label: "West Sussex"},
  {value: "reading", label: "Reading"},
  {value: "oxfordshire", label: "Oxfordshire"},
  {value: "kent", label: "Kent"},
  {value: "isle-of-wight", label: "Isle of Wight"},
  {value: "east-sussex", label: "East Sussex"},
  {value: "brighton-and-hove", label: "Brighton and Hove"},
  {value: "windsor-and-maidenhead", label: "Windsor and Maidenhead"},
  {value: "west-berkshire", label: "West Berkshire"},
  {value: "england-and-wales", label: "England and Wales"},
  {value: "england", label: "England"},
  {value: "woking", label: "Woking"},
  {value: "surrey-heath", label: "Surrey Heath"},
  {value: "spelthorne", label: "Spelthorne"},
  {value: "tandridge", label: "Tandridge"},
  {value: "mole-valley", label: "Mole Valley"},
  {value: "reigate-and-banstead", label: "Reigate and Banstead"},
  {value: "elmbridge", label: "Elmbridge"},
  {value: "waverley", label: "Waverley"},
  {value: "runnymede", label: "Runnymede"},
  {value: "guildford", label: "Guildford"},
  {value: "epsom-and-ewell", label: "Epsom and Ewell"},
  {value: "aylesbury-vale", label: "Aylesbury Vale"},
  {value: "south-bucks", label: "South Bucks"},
  {value: "wycombe", label: "Wycombe"},
  {value: "chiltern", label: "Chiltern"},
  {value: "havant", label: "Havant"},
  {value: "winchester", label: "Winchester"},
  {value: "fareham", label: "Fareham"},
  {value: "gosport", label: "Gosport"},
  {value: "rushmoor", label: "Rushmoor"},
  {value: "basingstoke-and-deane", label: "Basingstoke and Deane"},
  {value: "test-valley", label: "Test Valley"},
  {value: "eastleigh", label: "Eastleigh"},
  {value: "new-forest", label: "New Forest"},
  {value: "hart", label: "Hart"},
  {value: "east-hampshire", label: "East Hampshire"},
  {value: "horsham", label: "Horsham"},
  {value: "adur", label: "Adur"},
  {value: "crawley", label: "Crawley"},
  {value: "chichester", label: "Chichester"},
  {value: "arun", label: "Arun"},
  {value: "mid-sussex", label: "Mid Sussex"},
  {value: "worthing", label: "Worthing"},
  {value: "south-oxfordshire", label: "South Oxfordshire"},
  {value: "vale-of-white-horse", label: "Vale of White Horse"},
  {value: "west-oxfordshire", label: "West Oxfordshire"},
  {value: "oxford", label: "Oxford"},
  {value: "cherwell", label: "Cherwell"},
  {value: "maidstone", label: "Maidstone"},
  {value: "tunbridge-wells", label: "Tunbridge Wells"},
  {value: "swale", label: "Swale"},
  {value: "canterbury", label: "Canterbury"},
  {value: "dover", label: "Dover"},
  {value: "shepway", label: "Folkestone and Hythe"},
  {value: "ashford", label: "Ashford"},
  {value: "dartford", label: "Dartford"},
  {value: "tonbridge-and-malling", label: "Tonbridge and Malling"},
  {value: "sevenoaks", label: "Sevenoaks"},
  {value: "gravesham", label: "Gravesham"},
  {value: "thanet", label: "Thanet"},
  {value: "rother", label: "Rother"},
  {value: "lewes", label: "Lewes"},
  {value: "eastbourne", label: "Eastbourne"},
  {value: "hastings", label: "Hastings"},
  {value: "wealden", label: "Wealden"},
  {value: "west-midlands-region", label: "West Midlands Region"},
  {value: "west-midlands", label: "West Midlands"},
  {value: "yorkshire-and-the-humber", label: "Yorkshire and The Humber"},
  {value: "north-west", label: "North West"},
  {value: "south-west", label: "South West"},
  {value: "east-of-england", label: "East of England"},
  {value: "north-east", label: "North East"},
  {value: "wales", label: "Wales"},
  {value: "east-midlands", label: "East Midlands"},
  {value: "london", label: "London"},
  {value: "great-britain", label: "Great Britain"},
  {value: "warwickshire", label: "Warwickshire"},
  {value: "shropshire", label: "Shropshire"},
  {value: "stoke-on-trent", label: "Stoke-on-Trent"},
  {value: "staffordshire", label: "Staffordshire"},
  {value: "herefordshire", label: "Herefordshire"},
  {value: "worcestershire", label: "Worcestershire"},
  {value: "telford-and-wrekin", label: "Telford and Wrekin"},
  {value: "east-riding-of-yorkshire", label: "East Riding of Yorkshire"},
  {value: "west-yorkshire", label: "West Yorkshire"},
  {value: "south-yorkshire", label: "South Yorkshire"},
  {value: "north-lincolnshire", label: "North Lincolnshire"},
  {value: "north-east-lincolnshire", label: "North East Lincolnshire"},
  {value: "york", label: "York"},
  {value: "north-yorkshire", label: "North Yorkshire"},
  {value: "city-of-kingston-upon-hull", label: "City of Kingston upon Hull"},
  {value: "greater-manchester", label: "Greater Manchester"},
  {value: "merseyside", label: "Merseyside"},
  {value: "cheshire-east", label: "Cheshire East"},
  {value: "halton", label: "Halton"},
  {value: "cheshire-west-and-chester", label: "Cheshire West and Chester"},
  {value: "lancashire", label: "Lancashire"},
  {value: "blackpool", label: "Blackpool"},
  {value: "warrington", label: "Warrington"},
  {value: "cumbria", label: "Cumbria"},
  {value: "blackburn-with-darwen", label: "Blackburn with Darwen"},
  {value: "cornwall", label: "Cornwall"},
  {value: "gloucestershire", label: "Gloucestershire"},
  {value: "torbay", label: "Torbay"},
  {value: "wiltshire", label: "Wiltshire"},
  {value: "north-somerset", label: "North Somerset"},
  {value: "city-of-plymouth", label: "City of Plymouth"},
  {
    value: "bath-and-north-east-somerset",
    label: "Bath and North East Somerset",
  },
  {value: "city-of-bristol", label: "City of Bristol"},
  {value: "dorset", label: "Dorset"},
  {value: "devon", label: "Devon"},
  {value: "somerset", label: "Somerset"},
  {value: "swindon", label: "Swindon"},
  {value: "south-gloucestershire", label: "South Gloucestershire"},
  {value: "hertfordshire", label: "Hertfordshire"},
  {value: "thurrock", label: "Thurrock"},
  {value: "luton", label: "Luton"},
  {value: "essex", label: "Essex"},
  {value: "suffolk", label: "Suffolk"},
  {value: "cambridgeshire", label: "Cambridgeshire"},
  {value: "central-bedfordshire", label: "Central Bedfordshire"},
  {value: "bedford", label: "Bedford"},
  {value: "norfolk", label: "Norfolk"},
  {value: "city-of-peterborough", label: "City of Peterborough"},
  {value: "southend-on-sea", label: "Southend-on-Sea"},
  {value: "tyne-and-wear", label: "Tyne and Wear"},
  {value: "darlington", label: "Darlington"},
  {value: "northumberland", label: "Northumberland"},
  {value: "stockton-on-tees", label: "Stockton-on-Tees"},
  {value: "redcar-and-cleveland", label: "Redcar and Cleveland"},
  {value: "hartlepool", label: "Hartlepool"},
  {value: "middlesbrough", label: "Middlesbrough"},
  {value: "county-durham", label: "County Durham"},
  {value: "monmouthshire", label: "Monmouthshire"},
  {value: "conwy", label: "Conwy"},
  {value: "newport", label: "Newport"},
  {value: "bridgend", label: "Bridgend"},
  {value: "blaenau-gwent", label: "Blaenau Gwent"},
  {value: "flintshire", label: "Flintshire"},
  {value: "gwynedd", label: "Gwynedd"},
  {value: "wrexham", label: "Wrexham"},
  {value: "merthyr-tydfil", label: "Merthyr Tydfil"},
  {value: "cardiff", label: "Cardiff"},
  {value: "pembrokeshire", label: "Pembrokeshire"},
  {value: "caerphilly", label: "Caerphilly"},
  {value: "carmarthenshire", label: "Carmarthenshire"},
  {value: "denbighshire", label: "Denbighshire"},
  {value: "isle-of-anglesey", label: "Isle of Anglesey"},
  {value: "torfaen", label: "Torfaen"},
  {value: "ceredigion", label: "Ceredigion"},
  {value: "swansea", label: "Swansea"},
  {value: "vale-of-glamorgan", label: "Vale of Glamorgan"},
  {value: "neath-port-talbot", label: "Neath Port Talbot"},
  {value: "powys", label: "Powys"},
  {value: "rhondda-cynon-taf", label: "Rhondda Cynon Taf"},
  {value: "city-of-derby", label: "City of Derby"},
  {value: "city-of-nottingham", label: "City of Nottingham"},
  {value: "derbyshire", label: "Derbyshire"},
  {value: "nottinghamshire", label: "Nottinghamshire"},
  {value: "lincolnshire", label: "Lincolnshire"},
  {value: "leicester", label: "Leicester"},
  {value: "northamptonshire", label: "Northamptonshire"},
  {value: "leicestershire", label: "Leicestershire"},
  {value: "rutland", label: "Rutland"},
  {value: "inner-london", label: "Inner London"},
  {value: "outer-london", label: "Outer London"},
  {value: "scotland", label: "Scotland"},
  {value: "united-kingdom", label: "United Kingdom"},
  {value: "north-warwickshire", label: "North Warwickshire"},
  {value: "warwick", label: "Warwick"},
  {value: "stratford-on-avon", label: "Stratford-on-Avon"},
  {value: "rugby", label: "Rugby"},
  {value: "nuneaton-and-bedworth", label: "Nuneaton and Bedworth"},
  {value: "sandwell", label: "Sandwell"},
  {value: "dudley", label: "Dudley"},
  {value: "birmingham", label: "Birmingham"},
  {value: "solihull", label: "Solihull"},
  {value: "walsall", label: "Walsall"},
  {value: "coventry", label: "Coventry"},
  {value: "wolverhampton", label: "Wolverhampton"},
  {value: "cannock-chase", label: "Cannock Chase"},
  {value: "stafford", label: "Stafford"},
  {value: "east-staffordshire", label: "East Staffordshire"},
  {value: "lichfield", label: "Lichfield"},
  {value: "newcastle-under-lyme", label: "Newcastle-Under-Lyme"},
  {value: "tamworth", label: "Tamworth"},
  {value: "south-staffordshire", label: "South Staffordshire"},
  {value: "staffordshire-moorlands", label: "Staffordshire Moorlands"},
  {value: "wychavon", label: "Wychavon"},
  {value: "bromsgrove", label: "Bromsgrove"},
  {value: "redditch", label: "Redditch"},
  {value: "malvern-hills", label: "Malvern Hills"},
  {value: "wyre-forest", label: "Wyre Forest"},
  {value: "worcester", label: "Worcester"},
  {value: "leeds", label: "Leeds"},
  {value: "calderdale", label: "Calderdale"},
  {value: "kirklees", label: "Kirklees"},
  {value: "bradford", label: "Bradford"},
  {value: "wakefield", label: "Wakefield"},
  {value: "rotherham", label: "Rotherham"},
  {value: "sheffield", label: "Sheffield"},
  {value: "doncaster", label: "Doncaster"},
  {value: "barnsley", label: "Barnsley"},
  {value: "hambleton", label: "Hambleton"},
  {value: "harrogate", label: "Harrogate"},
  {value: "scarborough", label: "Scarborough"},
  {value: "richmondshire", label: "Richmondshire"},
  {value: "ryedale", label: "Ryedale"},
  {value: "selby", label: "Selby"},
  {value: "craven", label: "Craven"},
  {value: "rochdale", label: "Rochdale"},
  {value: "bury", label: "Bury"},
  {value: "wigan", label: "Wigan"},
  {value: "tameside", label: "Tameside"},
  {value: "trafford", label: "Trafford"},
  {value: "salford", label: "Salford"},
  {value: "manchester", label: "Manchester"},
  {value: "oldham", label: "Oldham"},
  {value: "stockport", label: "Stockport"},
  {value: "bolton", label: "Bolton"},
  {value: "st-helens", label: "St Helens"},
  {value: "knowsley", label: "Knowsley"},
  {value: "liverpool", label: "Liverpool"},
  {value: "sefton", label: "Sefton"},
  {value: "wirral", label: "Wirral"},
  {value: "south-ribble", label: "South Ribble"},
  {value: "burnley", label: "Burnley"},
  {value: "hyndburn", label: "Hyndburn"},
  {value: "preston", label: "Preston"},
  {value: "chorley", label: "Chorley"},
  {value: "rossendale", label: "Rossendale"},
  {value: "lancaster", label: "Lancaster"},
  {value: "ribble-valley", label: "Ribble Valley"},
  {value: "west-lancashire", label: "West Lancashire"},
  {value: "pendle", label: "Pendle"},
  {value: "fylde", label: "Fylde"},
  {value: "wyre", label: "Wyre"},
  {value: "eden", label: "Eden"},
  {value: "barrow-in-furness", label: "Barrow-In-Furness"},
  {value: "south-lakeland", label: "South Lakeland"},
  {value: "carlisle", label: "Carlisle"},
  {value: "allerdale", label: "Allerdale"},
  {value: "copeland", label: "Copeland"},
  {value: "stroud", label: "Stroud"},
  {value: "gloucester", label: "Gloucester"},
  {value: "tewkesbury", label: "Tewkesbury"},
  {value: "forest-of-dean", label: "Forest of Dean"},
  {value: "cotswold", label: "Cotswold"},
  {value: "cheltenham", label: "Cheltenham"},
  {value: "torridge", label: "Torridge"},
  {value: "east-devon", label: "East Devon"},
  {value: "west-devon", label: "West Devon"},
  {value: "teignbridge", label: "Teignbridge"},
  {value: "mid-devon", label: "Mid Devon"},
  {value: "south-hams", label: "South Hams"},
  {value: "exeter", label: "Exeter"},
  {value: "north-devon", label: "North Devon"},
  {value: "south-somerset", label: "South Somerset"},
  {value: "sedgemoor", label: "Sedgemoor"},
  {value: "mendip", label: "Mendip"},
  {value: "north-hertfordshire", label: "North Hertfordshire"},
  {value: "welwyn-hatfield", label: "Welwyn Hatfield"},
  {value: "three-rivers", label: "Three Rivers"},
  {value: "dacorum", label: "Dacorum"},
  {value: "hertsmere", label: "Hertsmere"},
  {value: "st-albans", label: "St Albans"},
  {value: "watford", label: "Watford"},
  {value: "stevenage", label: "Stevenage"},
  {value: "east-hertfordshire", label: "East Hertfordshire"},
  {value: "broxbourne", label: "Broxbourne"},
  {value: "uttlesford", label: "Uttlesford"},
  {value: "basildon", label: "Basildon"},
  {value: "epping-forest", label: "Epping Forest"},
  {value: "rochford", label: "Rochford"},
  {value: "harlow", label: "Harlow"},
  {value: "colchester", label: "Colchester"},
  {value: "braintree", label: "Braintree"},
  {value: "tendring", label: "Tendring"},
  {value: "castle-point", label: "Castle Point"},
  {value: "brentwood", label: "Brentwood"},
  {value: "chelmsford", label: "Chelmsford"},
  {value: "maldon", label: "Maldon"},
  {value: "ipswich", label: "Ipswich"},
  {value: "babergh", label: "Babergh"},
  {value: "mid-suffolk", label: "Mid Suffolk"},
  {value: "cambridge", label: "Cambridge"},
  {value: "huntingdonshire", label: "Huntingdonshire"},
  {value: "east-cambridgeshire", label: "East Cambridgeshire"},
  {value: "south-cambridgeshire", label: "South Cambridgeshire"},
  {value: "fenland", label: "Fenland"},
  {value: "broadland", label: "Broadland"},
  {value: "breckland", label: "Breckland"},
  {
    value: "king's-lynn-and-west-norfolk",
    label: "King's Lynn and West Norfolk",
  },
  {value: "norwich", label: "Norwich"},
  {value: "south-norfolk", label: "South Norfolk"},
  {value: "great-yarmouth", label: "Great Yarmouth"},
  {value: "north-norfolk", label: "North Norfolk"},
  {value: "newcastle-upon-tyne", label: "Newcastle upon Tyne"},
  {value: "gateshead", label: "Gateshead"},
  {value: "sunderland", label: "Sunderland"},
  {value: "north-tyneside", label: "North Tyneside"},
  {value: "south-tyneside", label: "South Tyneside"},
  {value: "amber-valley", label: "Amber Valley"},
  {value: "high-peak", label: "High Peak"},
  {value: "chesterfield", label: "Chesterfield"},
  {value: "bolsover", label: "Bolsover"},
  {value: "derbyshire-dales", label: "Derbyshire Dales"},
  {value: "erewash", label: "Erewash"},
  {value: "south-derbyshire", label: "South Derbyshire"},
  {value: "north-east-derbyshire", label: "North East Derbyshire"},
  {value: "broxtowe", label: "Broxtowe"},
  {value: "gedling", label: "Gedling"},
  {value: "rushcliffe", label: "Rushcliffe"},
  {value: "ashfield", label: "Ashfield"},
  {value: "mansfield", label: "Mansfield"},
  {value: "bassetlaw", label: "Bassetlaw"},
  {value: "newark-and-sherwood", label: "Newark and Sherwood"},
  {value: "south-holland", label: "South Holland"},
  {value: "south-kesteven", label: "South Kesteven"},
  {value: "north-kesteven", label: "North Kesteven"},
  {value: "west-lindsey", label: "West Lindsey"},
  {value: "east-lindsey", label: "East Lindsey"},
  {value: "lincoln", label: "Lincoln"},
  {value: "boston", label: "Boston"},
  {value: "daventry", label: "Daventry"},
  {value: "kettering", label: "Kettering"},
  {value: "wellingborough", label: "Wellingborough"},
  {value: "northampton", label: "Northampton"},
  {value: "south-northamptonshire", label: "South Northamptonshire"},
  {value: "east-northamptonshire", label: "East Northamptonshire"},
  {value: "corby", label: "Corby"},
  {value: "melton", label: "Melton"},
  {value: "charnwood", label: "Charnwood"},
  {value: "oadby-and-wigston", label: "Oadby and Wigston"},
  {value: "hinckley-and-bosworth", label: "Hinckley and Bosworth"},
  {value: "harborough", label: "Harborough"},
  {value: "blaby", label: "Blaby"},
  {value: "north-west-leicestershire", label: "North West Leicestershire"},
  {value: "tower-hamlets", label: "Tower Hamlets"},
  {value: "croydon", label: "Croydon"},
  {value: "richmond-upon-thames", label: "Richmond upon Thames"},
  {value: "city-of-westminster", label: "City of Westminster"},
  {value: "camden", label: "Camden"},
  {value: "greenwich", label: "Greenwich"},
  {value: "bexley", label: "Bexley"},
  {value: "hammersmith-and-fulham", label: "Hammersmith and Fulham"},
  {value: "islington", label: "Islington"},
  {value: "southwark", label: "Southwark"},
  {value: "brent", label: "Brent"},
  {value: "hounslow", label: "Hounslow"},
  {value: "hackney", label: "Hackney"},
  {value: "waltham-forest", label: "Waltham Forest"},
  {value: "kensington-and-chelsea", label: "Kensington and Chelsea"},
  {value: "wandsworth", label: "Wandsworth"},
  {value: "havering", label: "Havering"},
  {value: "redbridge", label: "Redbridge"},
  {value: "hillingdon", label: "Hillingdon"},
  {value: "sutton", label: "Sutton"},
  {value: "barking-and-dagenham", label: "Barking and Dagenham"},
  {value: "enfield", label: "Enfield"},
  {value: "harrow", label: "Harrow"},
  {value: "barnet", label: "Barnet"},
  {value: "ealing", label: "Ealing"},
  {value: "lambeth", label: "Lambeth"},
  {value: "kingston-upon-thames", label: "Kingston upon Thames"},
  {value: "lewisham", label: "Lewisham"},
  {value: "newham", label: "Newham"},
  {value: "merton", label: "Merton"},
  {value: "bromley", label: "Bromley"},
  {value: "haringey", label: "Haringey"},
  {value: "city-of-london", label: "City of London"},
  {value: "stirling", label: "Stirling"},
  {value: "clackmannanshire", label: "Clackmannanshire"},
  {value: "aberdeenshire", label: "Aberdeenshire"},
  {value: "south-ayrshire", label: "South Ayrshire"},
  {value: "shetland-islands", label: "Shetland Islands"},
  {value: "city-of-glasgow", label: "City of Glasgow"},
  {value: "renfrewshire", label: "Renfrewshire"},
  {value: "east-lothian", label: "East Lothian"},
  {value: "midlothian", label: "Midlothian"},
  {value: "orkney-islands", label: "Orkney Islands"},
  {value: "dumfries-and-galloway", label: "Dumfries and Galloway"},
  {value: "west-dunbartonshire", label: "West Dunbartonshire"},
  {value: "argyll-and-bute", label: "Argyll and Bute"},
  {value: "falkirk", label: "Falkirk"},
  {value: "scottish-borders", label: "Scottish Borders"},
  {value: "angus", label: "Angus"},
  {value: "north-lanarkshire", label: "North Lanarkshire"},
  {value: "perth-and-kinross", label: "Perth and Kinross"},
  {value: "east-ayrshire", label: "East Ayrshire"},
  {value: "city-of-dundee", label: "City of Dundee"},
  {value: "east-renfrewshire", label: "East Renfrewshire"},
  {value: "north-ayrshire", label: "North Ayrshire"},
  {value: "west-lothian", label: "West Lothian"},
  {value: "na-h-eileanan-siar", label: "Na h-Eileanan siar"},
  {value: "fife", label: "Fife"},
  {value: "east-dunbartonshire", label: "East Dunbartonshire"},
  {value: "inverclyde", label: "Inverclyde"},
  {value: "city-of-aberdeen", label: "City of Aberdeen"},
  {value: "south-lanarkshire", label: "South Lanarkshire"},
  {value: "city-of-edinburgh", label: "City of Edinburgh"},
  {value: "highland", label: "Highland"},
  {value: "moray", label: "Moray"},
  {value: "northern-ireland", label: "Northern Ireland"},
  {value: "belfast", label: "Belfast"},
  {value: "fermanagh-and-omagh", label: "Fermanagh and Omagh"},
  {value: "north-down-and-ards", label: "Ards and North Down"},
  {
    value: "armagh-banbridge-and-craigavon",
    label: "Armagh City Banbridge and Craigavon",
  },
  {value: "derry-and-strabane", label: "Derry City and Strabane"},
  {value: "newry-mourne-and-down", label: "Newry Mourne and Down"},
  {value: "lisburn-and-castlereagh", label: "Lisburn and Castlereagh"},
  {value: "antrim-and-newtownabbey", label: "Antrim and Newtownabbey"},
  {value: "mid-and-east-antrim", label: "Mid and East Antrim"},
  {value: "causeway-coast-and-glens", label: "Causeway Coast and Glens"},
  {value: "mid-ulster", label: "Mid Ulster"},
  {
    value: "bournemouth-christchurch-and-poole",
    label: "Bournemouth Christchurch and Poole",
  },
  {value: "somerset-west-and-taunton", label: "Somerset West and Taunton"},
  {value: "east-suffolk", label: "East Suffolk"},
  {value: "west-suffolk", label: "West Suffolk"},
];
